Combine include-packages and include-commands

diff --git a/maxipi b/maxipi
--- a/maxipi
+++ b/maxipi
@@ -460,6 +460,172 @@ msg() {
 
 }
 
+
+end() {
+  tput sgr0
+}
+
+e() {
+  tput sgr0
+}
+
+start() {
+  txt "$@"
+}
+s() {
+  txt "$@"
+}
+
+# This function is used to display color text
+txt() {
+  local mode="$1"
+  shift
+  if [[ "${mode^^}" == +(BLACK|RED|GREEN|YELLOW|BLUE|MAGENTA|CYAN) ]]; then
+    if ! [[ ${mode} =~ ^[0-9]$ ]]; then
+      case $(echo "${mode}" | tr '[:upper:]' '[:lower:]') in
+      black) mode=0 ;;
+      red) mode=1 ;;
+      green) mode=2 ;;
+      yellow) mode=3 ;;
+      blue) mode=4 ;;
+      magenta) mode=5 ;;
+      cyan) mode=6 ;;
+      end)
+        tput sgr0
+        return 0
+        ;;
+      # white or invalid color
+      white | *) mode=7 ;;
+      esac
+    fi
+    tput setaf ${mode}
+  elif [[ "${mode^^}" == +(NEWLINE|LINE) ]]; then
+    local count=$1 str=""
+    if [[ -z "${count}" || "${count}" -eq 0 || "${count}" -eq 1 ]]; then
+      return 0
+    fi
+    for ((i = 1; i <= count - 1; i++)); do
+      str="${str}\n"
+    done
+    if [ "$$" -eq "${BASHPID}" ]; then
+      for ((i = 1; i <= count - 2; i++)); do
+        str="${str}\n"
+      done
+      echo -e "${str}"
+    else
+      for ((i = 1; i <= count - 1; i++)); do
+        str="${str}\n"
+      done
+      # Using -e option here will not work if call inside string such as echo.
+      echo "${str}"
+    fi
+  elif [[ "${mode^^}" == +(NEWTAB|TAB) ]]; then
+    local count=$1 str=""
+    if [[ -z "${count}" || "${count}" -eq 0 || "${count}" -eq 1 ]]; then
+      return 0
+    fi
+
+    if [ "$$" -eq "${BASHPID}" ]; then
+      for ((i = 1; i <= count - 2; i++)); do
+        str="${str}\t"
+      done
+      echo -e "${str}"
+    else
+      for ((i = 1; i <= count - 1; i++)); do
+        str="${str}\t"
+      done
+      # Using -e option here will not work if call inside string such as echo.
+      echo "${str}"
+    fi
+  elif [[ "${mode^^}" == +(COLOR|COLOR|FOREGROUND|CLR|FG|C|F) ]]; then
+    local color=$1
+    if ! [[ $color =~ ^[0-9]$ ]]; then
+      case $(echo "${color}" | tr '[:upper:]' '[:lower:]') in
+      black) color=0 ;;
+      red) color=1 ;;
+      green) color=2 ;;
+      yellow) color=3 ;;
+      blue) color=4 ;;
+      magenta) color=5 ;;
+      cyan) color=6 ;;
+      end)
+        tput sgr0
+        return 0
+        ;;
+      # white or invalid color
+      white | *) color=7 ;;
+      esac
+    fi
+    tput setaf ${color}
+  # Set the background colour using ANSI escape
+  elif [[ "${mode^^}" == +(BACKGROUND|BG|B) ]]; then
+    local color=$1
+    if ! [[ $color =~ ^[0-9]$ ]]; then
+      case $(echo "${color}" | tr '[:upper:]' '[:lower:]') in
+      black) color=0 ;;
+      red) color=1 ;;
+      green) color=2 ;;
+      yellow) color=3 ;;
+      blue) color=4 ;;
+      magenta) color=5 ;;
+      cyan) color=6 ;;
+      end)
+        tput sgr0
+        return 0
+        ;;
+      # white or invalid color
+      white | *) color=7 ;;
+      esac
+    fi
+    tput setab ${color}
+
+  elif [[ ${mode^^} == +(BOLD|DIM|INVI|BLINK|REVERSE|ULINE|UNDERLINE|XULINE|FOCUS|STANDOUT|XFOCUS|BELL|ALERT|CLEAR|CLR|END) ]]; then
+    case $(echo "${mode}" | tr '[:upper:]' '[:lower:]') in
+    bold) mode="bold" ;;
+    dim) mode="dim" ;;
+    invi) mode="invis" ;;
+    blink) mode="blink" ;;
+    reverse) mode="rev" ;;
+    uline | underline) mode="smul" ;;
+    xuline) mode="rmul" ;;
+    focus | standout) mode="smso" ;;
+    xfocus) mode="rmso" ;;
+    bell | alert) mode="bel" ;;
+    clear | clr | end) mode="sgr0" ;;
+    *)
+      echo "Error, invalid argument supplied for text mode: ${mode}!"
+      exit 1
+      ;;
+    esac
+    tput "${mode}"
+    shopt -u nocasematch
+  # Note: Not all modes work for every terminal especially, bold, dim, invi, blink
+  elif [[ "${mode^^}" == +(MODE|M) ]]; then
+    local mode=$1
+    case $(echo "${mode}" | tr '[:upper:]' '[:lower:]') in
+    bold) mode="bold" ;;
+    dim) mode="dim" ;;
+    invi) mode="invis" ;;
+    blink) mode="blink" ;;
+    reverse) mode="rev" ;;
+    uline | underline) mode="smul" ;;
+    xuline) mode="rmul" ;;
+    focus | standout) mode="smso" ;;
+    xfocus) mode="rmso" ;;
+    bell | alert) mode="bel" ;;
+    clear | clr | end) mode="sgr0" ;;
+    *)
+      echo "Error, invalid argument supplied for text mode: ${mode}!"
+      exit 1
+      ;;
+    esac
+
+    tput "${mode}"
+  elif [[ "${mode^^}" == +(END|RESET|X|E) ]]; then
+    tput sgr0
+  fi
+}
+
 manual() {
   # This is a placeholder for manual function
   # You can add your own manual here
@@ -928,7 +1094,6 @@ is_valid() {
     fi
   # This will check if the given domain and IPv4 are resolved to each other
   elif [[ "${type}" == "ipv4-resolved" || "${type}" == "ipv4_resolved" ]]; then
-    # required_packages "dnsutils"
     local ipv4 ipv4_propagated domain
     ipv4="${data1}"
     domain="${data2}"
@@ -944,7 +1109,6 @@ is_valid() {
 
     # This will check if the given domain and IPv6 are resolved to each other
   elif [[ "${type}" == "ipv6-resolved" || "${type}" == "ipv6_resolved" ]]; then
-    # required_packages "dnsutils"
     local ipv6 ipv6_propagated domain
     ipv6="${data1}"
     domain="${data2}"
@@ -1228,9 +1392,6 @@ linode_api() {
   api_url="${LINODE_API_URL}"
 
   api_auth_string="Authorization: Bearer ${LINODE_API_KEY}"
-
-  # New code does not require linode-cli. We only need jq to manipulate json data
-  # required_packages "jq"
 
   # Return the number of item. Maximum page size is 500 (based on the API test value)
   linode_max_page_size=500
@@ -4520,8 +4681,6 @@ directadmin_api() {
 
   API_PROVIDER="directadmin"
 
-  #required_packages "jq"
-
   short_opts="h,c:,v,d,s,q"
   long_opts="help,config-file:,config:,verbose,debug,scripting,without-prompt,quite,sign-as:,signas:,login-as:,for-user:,username:,password:,for-username:,api-username:,\
   api-password:,package-name:,for-package-name:,ip-address:,netmask:,prefix:,add-ip-to-device:"
@@ -4890,7 +5049,7 @@ if ! command -v maxibuild >/dev/null 2>&1; then
 fi
 
 
-maxibuild --include-packages "curl,dnsutils,jq" --include-commands "ipcalc,mail,dig"
+maxibuild --include "curl,dnsutils,ipcalc,mail,jq"
 
 MAIL_BIN=$(command -v mail)
 LOG_PATH="${SCRIPT_PATH}/log"
